FROM almalinux
#RUN cd /tmp/ docker won't create below file in /tmp dircetory instead it creates in /root.
# To avoid this and create the file in your desired directory, then use WORKDIR
WORKDIR /tmp/ 
RUN touch hello.txt